version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    entrypoint: /bin/sh -c "python manage.py migrate && daphne todo_list.asgi:application -b 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SECRET_KEY=Jl$O)c~P7iG3VlC6?sQ5Tz8vI&fN^B4WDHJ@U*d$!2qnRP1(eA
      - DB_HOST=db
      - DB_NAME=prod
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - GOOGLE_OAUTH2_CLIENT_ID
      - GOOGLE_OAUTH2_CLIENT_SECRET
      - DEBUG=True

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
